#define VER_FILENAME AddinNative
#define VERSION_MAJOR     0
#define VERSION_MINOR     0
#define VERSION_REVISION  1
#define VERSION_BUILD     0
#define VERSION_FULL VERSION_MAJOR.VERSION_MINOR.VERSION_REVISION.VERSION_BUILD