Vagrant.configure("2") do |config|
	config.vm.define "server" do |vm1|
		vm1.vm.box = "eurolinux-vagrant/oracle-linux-8"
		vm1.vm.network "private_network", ip: "192.168.56.114"
		vm1.vm.hostname = "linux"
		
		# Копируем файл установщика 1С
		vm1.vm.provision "file", source: "rpm64_8_3_14_1694.tar.gz", destination: "/home/vagrant/distr/rpm64_8_3_14_1694.tar.gz"
		
		vm1.vm.provision "shell", inline: <<-SHELL
			sudo yum install mc -y
			cd distr
			sudo tar xzf rpm64_8_3_14_1694.tar.gz
			
			sudo yum localinstall *.rpm -y
			sudo yum install epel-release -y
			sudo yum install cabextract -y
			wget https://sourceforge.net/projects/mscorefonts2/files/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm/download -O msttcore-fonts-installer.rpm
			sudo yum localinstall msttcore-fonts-installer.rpm -y
			fc-cache –fv
			sudo yum install unixODBC -y
			systemctl start srv1cv83
			
			# Add the IP address and hostname POSTGRE to /etc/hosts
			echo "192.168.56.115	linuxpg" | sudo tee -a /etc/hosts
			grep "192.168.56.115	linuxpg" /etc/hosts
			
			sudo yum install git -y
			yum install cmake -y
			yum groupinstall -y "Development Tools" -y
			dnf install libuuid-devel -y
			
			
		SHELL
		
		# Trigger a reboot
		vm1.vm.provision :reload
	end
	
	config.vm.define "postgre" do |vm2|
		vm2.vm.box = "eurolinux-vagrant/oracle-linux-8"
		vm2.vm.network "private_network", ip: "192.168.56.115"
		vm2.vm.hostname = "linuxpg"
		
		vm2.vm.provision "shell", inline: <<-SHELL
		# Install required packages
		sudo yum install -y glibc-common glibc-locale-source glibc-langpack-ru

		# Generate the ru_RU.UTF-8 locale
		sudo localedef -v -c -i ru_RU -f UTF-8 ru_RU.UTF-8

		# Verify the locale generation
		locale -a | grep ru_RU

		# Set the locale as default
		echo 'LANG="ru_RU.UTF-8"' | sudo tee /etc/locale.conf
		echo 'LC_ALL="ru_RU.UTF-8"' | sudo tee -a /etc/locale.conf

		# Apply the locale settings
		source /etc/locale.conf

		# Restart services to apply locale settings if necessary
		sudo systemctl restart systemd-logind
		sudo yum install mc -y
		
		mkdir distr
		cd distr
		wget https://repo.postgrespro.ru/1c/1c-16/keys/pgpro-repo-add.sh
		
		sh pgpro-repo-add.sh
		yum install postgrespro-1c-16 -y
		/opt/pgpro/1c-16/bin/pg-setup initdb
		/opt/pgpro/1c-16/bin/pg-setup service enable
		/opt/pgpro/1c-16/bin/pg-setup service start
		
		sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'postgres';"
		
		SHELL
		
	end

end


  