# Use the Oracle Linux base image
FROM oraclelinux:8.10

# Set the maintainer label
LABEL maintainer="swd1986@yandex.ru"

RUN yum -y update && \
    yum -y install oracle-release-el8 && \
    yum -y install oraclelinux-release-el8 && \
    yum -y install zip unzip tar wget && \
    yum -y install glibc-langpack-en glibc-langpack-ru && \
    yum clean all

# Set environment variables
ENV LANG=ru_RU.UTF-8
ENV LANGUAGE=ru_RU:ru
ENV LC_ALL=ru_RU.UTF-8

# Set the working directory
WORKDIR /app

# Copy the application files into the container
COPY . /app

# Expose the port the application runs on
EXPOSE 22

# Define the command to run the application

